import { Phrase, PhraseBasePackage } from '../types/Phrase';

/**
 * Base inicial de frases (versão 1 do conteúdo).
 *
 * Regras seguidas na curadoria (seção 4 do MD):
 * - sem frases duplicadas ou quase-duplicadas;
 * - autoria só é atribuída quando razoavelmente conhecida;
 * - "Autor desconhecido" é usado quando não há confirmação segura;
 * - nenhum conteúdo ofensivo, discriminatório ou inadequado.
 *
 * Este arquivo é o pacote v1 (168 frases: 65 da curadoria inicial
 * + 103 fornecidas pelo produto, já deduplicadas). Uma futura atualização de
 * conteúdo deve criar um novo array (ex: phrasesData.v2.ts) somando
 * frases com ids novos aos ids já existentes — nunca reescrevendo um
 * id já publicado. Ver src/services/phraseSyncService.ts (Fase 3) para
 * a lógica de merge com o banco local.
 */
const frases: Phrase[] = [
  { id: 'frase-001', texto: 'A jornada de mil quilômetros começa com um único passo.', autor: 'Lao Tsé', categoria: 'Persistência', ativo: true },
  { id: 'frase-002', texto: 'Não é o mais forte que sobrevive, nem o mais inteligente, mas o que melhor se adapta às mudanças.', autor: 'Autor desconhecido', categoria: 'Superação', ativo: true },
  { id: 'frase-003', texto: 'Conhece-te a ti mesmo.', autor: 'Sócrates', categoria: 'Sabedoria', ativo: true },
  { id: 'frase-004', texto: 'Não é o que nos acontece, mas como reagimos ao que nos acontece, que importa.', autor: 'Epicteto', categoria: 'Reflexão', ativo: true },
  { id: 'frase-005', texto: 'A sorte favorece a mente preparada.', autor: 'Louis Pasteur', categoria: 'Foco', ativo: true },
  { id: 'frase-006', texto: 'Quem tem um porquê para viver pode suportar quase todos os comos.', autor: 'Friedrich Nietzsche', categoria: 'Vida', ativo: true },
  { id: 'frase-007', texto: 'O que fazemos por nós mesmos morre conosco. O que fazemos pelos outros permanece.', autor: 'Albert Pine', categoria: 'Relacionamentos', ativo: true },
  { id: 'frase-008', texto: 'Feliz aquele que transfere o que sabe e aprende o que ensina.', autor: 'Cora Coralina', categoria: 'Estudos', ativo: true },
  { id: 'frase-009', texto: 'Antes de ganhar, é preciso aprender a perder com dignidade.', autor: 'Autor desconhecido', categoria: 'Superação', ativo: true },
  { id: 'frase-010', texto: 'Trabalhar com amor é dar à luz um pedaço de si mesmo.', autor: 'Autor desconhecido', categoria: 'Trabalho', ativo: true },
  { id: 'frase-011', texto: 'Um passo à frente e você não está mais no mesmo lugar.', autor: 'Chico Science', categoria: 'Motivação', ativo: true },
  { id: 'frase-012', texto: 'Só se vê bem com o coração; o essencial é invisível aos olhos.', autor: 'Antoine de Saint-Exupéry', categoria: 'Reflexão', ativo: true },
  { id: 'frase-013', texto: 'A persistência é o caminho do êxito.', autor: 'Charles Chaplin', categoria: 'Persistência', ativo: true },
  { id: 'frase-014', texto: 'Ninguém é tão grande que não possa aprender, nem tão pequeno que não possa ensinar.', autor: 'Esopo', categoria: 'Sabedoria', ativo: true },
  { id: 'frase-015', texto: 'O importante não é vencer todos os dias, mas lutar sempre.', autor: 'Waldemar Valle Martins', categoria: 'Disciplina', ativo: true },
  { id: 'frase-016', texto: 'Gratidão é a memória do coração.', autor: 'Jean Baptiste Massieu', categoria: 'Gratidão', ativo: true },
  { id: 'frase-017', texto: 'Nada do que foi será de novo do jeito que já foi um dia.', autor: 'Renato Russo', categoria: 'Vida', ativo: true },
  { id: 'frase-018', texto: 'Faça o que puder, com o que tiver, no lugar em que estiver.', autor: 'Theodore Roosevelt', categoria: 'Motivação', ativo: true },
  { id: 'frase-019', texto: 'A disciplina é a ponte entre metas e conquistas.', autor: 'Jim Rohn', categoria: 'Disciplina', ativo: true },
  { id: 'frase-020', texto: 'Rir é o remédio mais barato que existe, e ainda vem sem bula.', autor: 'Autor desconhecido', categoria: 'Humor/reflexão leve', ativo: true },
  { id: 'frase-021', texto: 'A vida é aquilo que acontece enquanto você está ocupado fazendo outros planos.', autor: 'John Lennon', categoria: 'Vida', ativo: true },
  { id: 'frase-022', texto: 'Não temas ir devagar, teme apenas ficar parado.', autor: 'Provérbio chinês', categoria: 'Persistência', ativo: true },
  { id: 'frase-023', texto: 'O sucesso é a soma de pequenos esforços repetidos dia após dia.', autor: 'Robert Collier', categoria: 'Sucesso', ativo: true },
  { id: 'frase-024', texto: 'Coragem não é a ausência de medo, mas o triunfo sobre ele.', autor: 'Nelson Mandela', categoria: 'Coragem', ativo: true },
  { id: 'frase-025', texto: 'A amizade multiplica os bens e divide os males.', autor: 'Cícero', categoria: 'Relacionamentos', ativo: true },
  { id: 'frase-026', texto: 'Aprender é a única coisa de que a mente nunca se cansa, nunca tem medo e nunca se arrepende.', autor: 'Leonardo da Vinci', categoria: 'Estudos', ativo: true },
  { id: 'frase-027', texto: 'Quem sabe faz a hora, não espera acontecer.', autor: 'Geraldo Vandré', categoria: 'Motivação', ativo: true },
  { id: 'frase-028', texto: 'Cair não é fracasso; fracasso é ficar onde caiu.', autor: 'Autor desconhecido', categoria: 'Superação', ativo: true },
  { id: 'frase-029', texto: 'A verdadeira riqueza está em contentar-se com pouco.', autor: 'Sêneca', categoria: 'Sabedoria', ativo: true },
  { id: 'frase-030', texto: 'Não deixe que o barulho da opinião alheia abafe sua voz interior.', autor: 'Steve Jobs', categoria: 'Foco', ativo: true },
  { id: 'frase-031', texto: 'Cada dia é uma nova oportunidade de mudar a sua vida.', autor: 'Autor desconhecido', categoria: 'Motivação', ativo: true },
  { id: 'frase-032', texto: 'A gratidão transforma o que temos em suficiente.', autor: 'Autor desconhecido', categoria: 'Gratidão', ativo: true },
  { id: 'frase-033', texto: 'Onde há disciplina, a liberdade cresce em terreno seguro.', autor: 'Autor desconhecido', categoria: 'Disciplina', ativo: true },
  { id: 'frase-034', texto: 'O trabalho duro vence o talento quando o talento não trabalha duro.', autor: 'Tim Notke', categoria: 'Trabalho', ativo: true },
  { id: 'frase-035', texto: 'Feliz é quem transfere o que sabe e aprende o que ensina, sem perder tempo comparando.', autor: 'Autor desconhecido', categoria: 'Felicidade', ativo: true },
  { id: 'frase-036', texto: 'Quem cai e se levanta é mais forte do que quem nunca caiu.', autor: 'Provérbio popular', categoria: 'Superação', ativo: true },
  { id: 'frase-037', texto: 'A calma é a maior arma contra as dificuldades.', autor: 'Marco Aurélio', categoria: 'Reflexão', ativo: true },
  { id: 'frase-038', texto: 'Não existe caminho para a felicidade: a felicidade é o caminho.', autor: 'Mahatma Gandhi', categoria: 'Felicidade', ativo: true },
  { id: 'frase-039', texto: 'Só se aprende de duas maneiras: pela dor ou pela repetição.', autor: 'Autor desconhecido', categoria: 'Estudos', ativo: true },
  { id: 'frase-040', texto: 'O foco é dizer não a mil boas ideias para dizer sim a uma só.', autor: 'Autor desconhecido', categoria: 'Foco', ativo: true },
  { id: 'frase-041', texto: 'Grandes conquistas nascem de decisões pequenas, tomadas todos os dias.', autor: 'Autor desconhecido', categoria: 'Sucesso', ativo: true },
  { id: 'frase-042', texto: 'A coragem começa com pequenos passos, não com grandes discursos.', autor: 'Autor desconhecido', categoria: 'Coragem', ativo: true },
  { id: 'frase-043', texto: 'Um amigo verdadeiro é quem sabe a sua história e ainda assim gosta de você.', autor: 'Elbert Hubbard', categoria: 'Relacionamentos', ativo: true },
  { id: 'frase-044', texto: 'A vida é curta demais para ser vivida com medo.', autor: 'Autor desconhecido', categoria: 'Vida', ativo: true },
  { id: 'frase-045', texto: 'Quem planta paciência colhe segurança.', autor: 'Provérbio popular', categoria: 'Persistência', ativo: true },
  { id: 'frase-046', texto: 'Sabedoria não é saber muito, mas saber o que realmente importa.', autor: 'Autor desconhecido', categoria: 'Sabedoria', ativo: true },
  { id: 'frase-047', texto: 'Um pouco de humor evita que os problemas fiquem pesados demais.', autor: 'Autor desconhecido', categoria: 'Humor/reflexão leve', ativo: true },
  { id: 'frase-048', texto: 'O melhor projeto que você vai construir é a sua própria disciplina diária.', autor: 'Autor desconhecido', categoria: 'Disciplina', ativo: true },
  { id: 'frase-049', texto: 'Gratidão não é sobre o que falta, é sobre o que já chegou.', autor: 'Autor desconhecido', categoria: 'Gratidão', ativo: true },
  { id: 'frase-050', texto: 'Fazer bem feito é o que separa um trabalho de um legado.', autor: 'Autor desconhecido', categoria: 'Trabalho', ativo: true },
  { id: 'frase-051', texto: 'A persistência realiza o impossível.', autor: 'Provérbio popular', categoria: 'Persistência', ativo: true },
  { id: 'frase-052', texto: 'Não julgue cada dia pela colheita que você recolhe, mas pelas sementes que planta.', autor: 'Robert Louis Stevenson', categoria: 'Reflexão', ativo: true },
  { id: 'frase-053', texto: 'Estudar é adiantar-se ao futuro que ainda vai chegar.', autor: 'Autor desconhecido', categoria: 'Estudos', ativo: true },
  { id: 'frase-054', texto: 'Um sorriso não custa nada e vale muito.', autor: 'Provérbio popular', categoria: 'Felicidade', ativo: true },
  { id: 'frase-055', texto: 'Toda grande mudança parece impossível até que ela aconteça.', autor: 'Nelson Mandela', categoria: 'Motivação', ativo: true },
  { id: 'frase-056', texto: 'Foco não é fazer mais coisas, é eliminar o que não importa.', autor: 'Autor desconhecido', categoria: 'Foco', ativo: true },
  { id: 'frase-057', texto: 'O sucesso é ir de fracasso em fracasso sem perder o entusiasmo.', autor: 'Winston Churchill', categoria: 'Sucesso', ativo: true },
  { id: 'frase-058', texto: 'A coragem de começar já separa quem sonha de quem realiza.', autor: 'Autor desconhecido', categoria: 'Coragem', ativo: true },
  { id: 'frase-059', texto: 'Quem caminha sozinho pode até chegar mais rápido, mas quem vai acompanhado chega mais longe.', autor: 'Provérbio africano', categoria: 'Relacionamentos', ativo: true },
  { id: 'frase-060', texto: 'A vida não se mede pelo número de respirações que damos, mas pelos momentos que nos tiram o fôlego.', autor: 'Autor desconhecido', categoria: 'Vida', ativo: true },
  { id: 'frase-061', texto: 'Ser grato pelo pouco é o primeiro passo para receber o muito.', autor: 'Autor desconhecido', categoria: 'Gratidão', ativo: true },
  { id: 'frase-062', texto: 'A sabedoria começa no momento em que você admite não saber tudo.', autor: 'Autor desconhecido', categoria: 'Sabedoria', ativo: true },
  { id: 'frase-063', texto: 'Levar a vida com leveza também é uma forma de coragem.', autor: 'Autor desconhecido', categoria: 'Humor/reflexão leve', ativo: true },
  { id: 'frase-064', texto: 'Disciplina é escolher entre o que você quer agora e o que você quer mais.', autor: 'Autor desconhecido', categoria: 'Disciplina', ativo: true },
  { id: 'frase-065', texto: 'O trabalho bem feito de hoje é o descanso tranquilo de amanhã.', autor: 'Autor desconhecido', categoria: 'Trabalho', ativo: true },
  { id: 'frase-066', texto: 'A melhor maneira de prever o futuro é criá-lo.', autor: 'Peter Drucker', categoria: 'Motivação', ativo: true },
  { id: 'frase-067', texto: 'Não espere por oportunidades. Crie-as.', autor: 'Autor desconhecido', categoria: 'Motivação', ativo: true },
  { id: 'frase-068', texto: 'O único modo de fazer um excelente trabalho é amar o que você faz.', autor: 'Steve Jobs', categoria: 'Trabalho', ativo: true },
  { id: 'frase-069', texto: 'Você deve ser a mudança que deseja ver no mundo.', autor: 'Mahatma Gandhi', categoria: 'Motivação', ativo: true },
  { id: 'frase-070', texto: 'Grandes coisas são feitas por uma série de pequenas coisas reunidas.', autor: 'Vincent van Gogh', categoria: 'Persistência', ativo: true },
  { id: 'frase-071', texto: 'Acredite que você pode, assim você já está no meio do caminho.', autor: 'Theodore Roosevelt', categoria: 'Motivação', ativo: true },
  { id: 'frase-072', texto: 'Não conte os dias, faça os dias contarem.', autor: 'Muhammad Ali', categoria: 'Vida', ativo: true },
  { id: 'frase-073', texto: 'Nossa maior glória não é nunca cair, mas levantar a cada queda.', autor: 'Confúcio', categoria: 'Superação', ativo: true },
  { id: 'frase-074', texto: 'O que você faz hoje pode melhorar todos os seus amanhãs.', autor: 'Ralph Marston', categoria: 'Motivação', ativo: true },
  { id: 'frase-075', texto: 'A única pessoa que você está destinado a se tornar é a pessoa que decide ser.', autor: 'Ralph Waldo Emerson', categoria: 'Reflexão', ativo: true },
  { id: 'frase-076', texto: 'O futuro pertence àqueles que acreditam na beleza de seus sonhos.', autor: 'Eleanor Roosevelt', categoria: 'Motivação', ativo: true },
  { id: 'frase-077', texto: 'Faça cada dia a sua obra-prima.', autor: 'John Wooden', categoria: 'Disciplina', ativo: true },
  { id: 'frase-078', texto: 'A felicidade não é algo pronto. Ela vem de suas próprias ações.', autor: 'Dalai Lama', categoria: 'Felicidade', ativo: true },
  { id: 'frase-079', texto: 'A vida é feita de escolhas, e cada escolha constrói um pouco do nosso caminho.', autor: 'Autor desconhecido', categoria: 'Vida', ativo: true },
  { id: 'frase-080', texto: 'O começo é sempre o momento mais difícil, mas também é o que torna o caminho possível.', autor: 'Autor desconhecido', categoria: 'Coragem', ativo: true },
  { id: 'frase-081', texto: 'Pequenos passos também levam a grandes destinos.', autor: 'Autor desconhecido', categoria: 'Persistência', ativo: true },
  { id: 'frase-082', texto: 'Não tenha medo de recomeçar. Às vezes, é no recomeço que encontramos nossa melhor versão.', autor: 'Autor desconhecido', categoria: 'Superação', ativo: true },
  { id: 'frase-083', texto: 'O aprendizado é um tesouro que acompanha seu dono em todos os lugares.', autor: 'Provérbio chinês', categoria: 'Estudos', ativo: true },
  { id: 'frase-084', texto: 'Não compare o seu capítulo um com o capítulo vinte de outra pessoa.', autor: 'Autor desconhecido', categoria: 'Reflexão', ativo: true },
  { id: 'frase-085', texto: 'Cada manhã é uma nova oportunidade de fazer diferente.', autor: 'Autor desconhecido', categoria: 'Motivação', ativo: true },
  { id: 'frase-086', texto: 'O sucesso começa quando você decide não desistir.', autor: 'Autor desconhecido', categoria: 'Sucesso', ativo: true },
  { id: 'frase-087', texto: 'Acredite no processo, mesmo quando os resultados ainda não apareceram.', autor: 'Autor desconhecido', categoria: 'Persistência', ativo: true },
  { id: 'frase-088', texto: 'O tempo que você dedica ao seu crescimento nunca é tempo perdido.', autor: 'Autor desconhecido', categoria: 'Estudos', ativo: true },
  { id: 'frase-089', texto: 'Não é preciso enxergar todo o caminho para dar o primeiro passo.', autor: 'Autor desconhecido', categoria: 'Coragem', ativo: true },
  { id: 'frase-090', texto: 'O esforço de hoje é a experiência que fortalece o amanhã.', autor: 'Autor desconhecido', categoria: 'Persistência', ativo: true },
  { id: 'frase-091', texto: 'Seja paciente com seu progresso.', autor: 'Autor desconhecido', categoria: 'Persistência', ativo: true },
  { id: 'frase-092', texto: 'A diferença entre tentar e conseguir muitas vezes está em tentar mais uma vez.', autor: 'Autor desconhecido', categoria: 'Persistência', ativo: true },
  { id: 'frase-093', texto: 'Você não precisa ser perfeito para começar; precisa apenas começar.', autor: 'Autor desconhecido', categoria: 'Coragem', ativo: true },
  { id: 'frase-094', texto: 'A melhor competição é aquela que você trava contra quem foi ontem.', autor: 'Autor desconhecido', categoria: 'Superação', ativo: true },
  { id: 'frase-095', texto: 'O conhecimento cresce quando é compartilhado.', autor: 'Autor desconhecido', categoria: 'Estudos', ativo: true },
  { id: 'frase-096', texto: 'Erros são pontos de partida para quem escolhe aprender com eles.', autor: 'Autor desconhecido', categoria: 'Superação', ativo: true },
  { id: 'frase-097', texto: 'Não transforme um dia difícil em uma vida difícil.', autor: 'Autor desconhecido', categoria: 'Reflexão', ativo: true },
  { id: 'frase-098', texto: 'Depois da tempestade, o céu sempre encontra uma maneira de clarear.', autor: 'Autor desconhecido', categoria: 'Superação', ativo: true },
  { id: 'frase-099', texto: 'Algumas portas só se abrem quando você decide bater.', autor: 'Autor desconhecido', categoria: 'Coragem', ativo: true },
  { id: 'frase-100', texto: 'Sonhos precisam de coragem para nascer e disciplina para crescer.', autor: 'Autor desconhecido', categoria: 'Disciplina', ativo: true },
  { id: 'frase-101', texto: 'O que parece pequeno hoje pode se tornar extraordinário amanhã.', autor: 'Autor desconhecido', categoria: 'Persistência', ativo: true },
  { id: 'frase-102', texto: 'A distância até o objetivo diminui a cada passo.', autor: 'Autor desconhecido', categoria: 'Foco', ativo: true },
  { id: 'frase-103', texto: 'Não desista só porque o resultado está demorando.', autor: 'Autor desconhecido', categoria: 'Persistência', ativo: true },
  { id: 'frase-104', texto: 'A força que você procura pode estar justamente na decisão de continuar.', autor: 'Autor desconhecido', categoria: 'Superação', ativo: true },
  { id: 'frase-105', texto: 'O melhor investimento que você pode fazer é investir em si mesmo.', autor: 'Autor desconhecido', categoria: 'Estudos', ativo: true },
  { id: 'frase-106', texto: 'A disciplina faz nos dias difíceis aquilo que a motivação faz nos dias bons.', autor: 'Autor desconhecido', categoria: 'Disciplina', ativo: true },
  { id: 'frase-107', texto: 'Quem aprende a esperar também aprende a valorizar.', autor: 'Autor desconhecido', categoria: 'Sabedoria', ativo: true },
  { id: 'frase-108', texto: 'Não deixe que o medo de falhar seja maior que a vontade de tentar.', autor: 'Autor desconhecido', categoria: 'Coragem', ativo: true },
  { id: 'frase-109', texto: 'Toda conquista começa com uma intenção transformada em ação.', autor: 'Autor desconhecido', categoria: 'Foco', ativo: true },
  { id: 'frase-110', texto: 'Faça hoje algo pelo qual seu futuro agradecerá.', autor: 'Autor desconhecido', categoria: 'Motivação', ativo: true },
  { id: 'frase-111', texto: 'O caminho pode ser longo, mas cada passo tem seu valor.', autor: 'Autor desconhecido', categoria: 'Persistência', ativo: true },
  { id: 'frase-112', texto: 'A determinação nasce quando o desejo encontra um propósito.', autor: 'Autor desconhecido', categoria: 'Foco', ativo: true },
  { id: 'frase-113', texto: 'Não espere o momento perfeito; faça o momento valer a pena.', autor: 'Autor desconhecido', categoria: 'Motivação', ativo: true },
  { id: 'frase-114', texto: 'A mudança começa quando permanecer igual deixa de ser uma opção.', autor: 'Autor desconhecido', categoria: 'Superação', ativo: true },
  { id: 'frase-115', texto: 'A simplicidade muitas vezes esconde as coisas mais importantes da vida.', autor: 'Autor desconhecido', categoria: 'Sabedoria', ativo: true },
  { id: 'frase-116', texto: 'Valorize o que você tem enquanto trabalha pelo que deseja.', autor: 'Autor desconhecido', categoria: 'Gratidão', ativo: true },
  { id: 'frase-117', texto: 'A felicidade está mais nos momentos que vivemos do que nas coisas que acumulamos.', autor: 'Autor desconhecido', categoria: 'Felicidade', ativo: true },
  { id: 'frase-118', texto: 'Aprenda a apreciar o caminho, não apenas o destino.', autor: 'Autor desconhecido', categoria: 'Vida', ativo: true },
  { id: 'frase-119', texto: 'Um coração grato encontra motivos para sorrir todos os dias.', autor: 'Autor desconhecido', categoria: 'Gratidão', ativo: true },
  { id: 'frase-120', texto: 'A vida não precisa ser perfeita para ser extraordinária.', autor: 'Autor desconhecido', categoria: 'Felicidade', ativo: true },
  { id: 'frase-121', texto: 'Às vezes, desacelerar é a melhor maneira de perceber o que realmente importa.', autor: 'Autor desconhecido', categoria: 'Reflexão', ativo: true },
  { id: 'frase-122', texto: 'Cuide dos pequenos momentos; são eles que formam uma grande vida.', autor: 'Autor desconhecido', categoria: 'Vida', ativo: true },
  { id: 'frase-123', texto: 'A verdadeira riqueza está naquilo que dinheiro nenhum consegue comprar.', autor: 'Autor desconhecido', categoria: 'Sabedoria', ativo: true },
  { id: 'frase-124', texto: 'O conhecimento abre portas que a força jamais conseguiria abrir.', autor: 'Autor desconhecido', categoria: 'Estudos', ativo: true },
  { id: 'frase-125', texto: 'Quem continua aprendendo nunca deixa de crescer.', autor: 'Autor desconhecido', categoria: 'Estudos', ativo: true },
  { id: 'frase-126', texto: 'A mente que se abre para aprender nunca volta ao tamanho original.', autor: 'Autor desconhecido', categoria: 'Estudos', ativo: true },
  { id: 'frase-127', texto: 'A educação é a arma mais poderosa que você pode usar para mudar o mundo.', autor: 'Nelson Mandela', categoria: 'Estudos', ativo: true },
  { id: 'frase-128', texto: 'Aprender é descobrir que sempre existe algo novo para conhecer.', autor: 'Autor desconhecido', categoria: 'Estudos', ativo: true },
  { id: 'frase-129', texto: 'A curiosidade é o primeiro passo para o conhecimento.', autor: 'Autor desconhecido', categoria: 'Estudos', ativo: true },
  { id: 'frase-130', texto: 'Não tenha vergonha de não saber; tenha curiosidade para aprender.', autor: 'Autor desconhecido', categoria: 'Estudos', ativo: true },
  { id: 'frase-131', texto: 'Cada erro compreendido acrescenta uma nova ferramenta à sua experiência.', autor: 'Autor desconhecido', categoria: 'Estudos', ativo: true },
  { id: 'frase-132', texto: 'O conhecimento adquirido hoje pode transformar as decisões de amanhã.', autor: 'Autor desconhecido', categoria: 'Sabedoria', ativo: true },
  { id: 'frase-133', texto: 'Quem pergunta aprende; quem observa também.', autor: 'Autor desconhecido', categoria: 'Estudos', ativo: true },
  { id: 'frase-134', texto: 'A coragem começa quando você decide enfrentar aquilo que gostaria de evitar.', autor: 'Autor desconhecido', categoria: 'Coragem', ativo: true },
  { id: 'frase-135', texto: 'Ser forte também significa saber quando pedir ajuda.', autor: 'Autor desconhecido', categoria: 'Coragem', ativo: true },
  { id: 'frase-136', texto: 'Você é mais capaz do que imagina quando decide não desistir.', autor: 'Autor desconhecido', categoria: 'Superação', ativo: true },
  { id: 'frase-137', texto: 'O medo pode bater à porta; cabe a você decidir se irá deixá-lo entrar.', autor: 'Autor desconhecido', categoria: 'Coragem', ativo: true },
  { id: 'frase-138', texto: 'A confiança cresce quando você cumpre as promessas que faz a si mesmo.', autor: 'Autor desconhecido', categoria: 'Disciplina', ativo: true },
  { id: 'frase-139', texto: 'Não deixe uma derrota definir quem você é.', autor: 'Autor desconhecido', categoria: 'Superação', ativo: true },
  { id: 'frase-140', texto: 'Há forças que só descobrimos quando somos colocados à prova.', autor: 'Autor desconhecido', categoria: 'Superação', ativo: true },
  { id: 'frase-141', texto: 'Levantar depois de cair também é uma forma de vitória.', autor: 'Autor desconhecido', categoria: 'Superação', ativo: true },
  { id: 'frase-142', texto: 'A excelência nasce da atenção aos detalhes.', autor: 'Autor desconhecido', categoria: 'Trabalho', ativo: true },
  { id: 'frase-143', texto: 'Faça bem feito aquilo que estiver ao seu alcance hoje.', autor: 'Autor desconhecido', categoria: 'Trabalho', ativo: true },
  { id: 'frase-144', texto: 'A qualidade de uma conquista também está na dedicação colocada no caminho.', autor: 'Autor desconhecido', categoria: 'Trabalho', ativo: true },
  { id: 'frase-145', texto: 'Grandes resultados são construídos quando ninguém está olhando.', autor: 'Autor desconhecido', categoria: 'Disciplina', ativo: true },
  { id: 'frase-146', texto: 'A consistência transforma esforço em resultado.', autor: 'Autor desconhecido', categoria: 'Disciplina', ativo: true },
  { id: 'frase-147', texto: 'Não procure atalhos para aquilo que merece ser construído com cuidado.', autor: 'Autor desconhecido', categoria: 'Trabalho', ativo: true },
  { id: 'frase-148', texto: 'O talento pode abrir uma porta, mas a dedicação ajuda a mantê-la aberta.', autor: 'Autor desconhecido', categoria: 'Trabalho', ativo: true },
  { id: 'frase-149', texto: 'O trabalho de hoje é a base das conquistas de amanhã.', autor: 'Autor desconhecido', categoria: 'Trabalho', ativo: true },
  { id: 'frase-150', texto: 'Um objetivo sem ação continua sendo apenas uma intenção.', autor: 'Autor desconhecido', categoria: 'Foco', ativo: true },
  { id: 'frase-151', texto: 'Transforme seus planos em pequenas ações diárias.', autor: 'Autor desconhecido', categoria: 'Foco', ativo: true },
  { id: 'frase-152', texto: 'Quem sabe onde quer chegar encontra mais facilmente o próximo passo.', autor: 'Autor desconhecido', categoria: 'Foco', ativo: true },
  { id: 'frase-153', texto: 'Metas dão direção; disciplina dá continuidade.', autor: 'Autor desconhecido', categoria: 'Foco', ativo: true },
  { id: 'frase-154', texto: 'Não subestime o poder de fazer algo um pouco melhor todos os dias.', autor: 'Autor desconhecido', categoria: 'Disciplina', ativo: true },
  { id: 'frase-155', texto: 'O futuro é construído pelas escolhas que fazemos no presente.', autor: 'Autor desconhecido', categoria: 'Reflexão', ativo: true },
  { id: 'frase-156', texto: 'Planejar é transformar desejos em caminhos possíveis.', autor: 'Autor desconhecido', categoria: 'Foco', ativo: true },
  { id: 'frase-157', texto: 'Uma decisão pequena pode mudar completamente o rumo de uma história.', autor: 'Autor desconhecido', categoria: 'Reflexão', ativo: true },
  { id: 'frase-158', texto: 'Não espere ter todas as respostas para começar a buscar soluções.', autor: 'Autor desconhecido', categoria: 'Coragem', ativo: true },
  { id: 'frase-159', texto: 'Quando o propósito é forte, os obstáculos deixam de ser o fim.', autor: 'Autor desconhecido', categoria: 'Foco', ativo: true },
  { id: 'frase-160', texto: 'Seja gentil: você nunca sabe qual batalha alguém está enfrentando.', autor: 'Autor desconhecido', categoria: 'Relacionamentos', ativo: true },
  { id: 'frase-161', texto: 'Palavras podem ser pequenas, mas o impacto delas pode durar uma vida inteira.', autor: 'Autor desconhecido', categoria: 'Relacionamentos', ativo: true },
  { id: 'frase-162', texto: 'A gentileza é uma forma simples de tornar o mundo melhor.', autor: 'Autor desconhecido', categoria: 'Relacionamentos', ativo: true },
  { id: 'frase-163', texto: 'Escutar também é uma forma de cuidar.', autor: 'Autor desconhecido', categoria: 'Relacionamentos', ativo: true },
  { id: 'frase-164', texto: 'Um sorriso sincero pode mudar o dia de alguém.', autor: 'Autor desconhecido', categoria: 'Relacionamentos', ativo: true },
  { id: 'frase-165', texto: 'Trate as pessoas com respeito, mesmo quando pensar diferente delas.', autor: 'Autor desconhecido', categoria: 'Relacionamentos', ativo: true },
  { id: 'frase-166', texto: 'A melhor maneira de espalhar luz é não guardar toda a luz para si.', autor: 'Autor desconhecido', categoria: 'Relacionamentos', ativo: true },
  { id: 'frase-167', texto: 'Nunca é desperdício fazer o bem.', autor: 'Autor desconhecido', categoria: 'Relacionamentos', ativo: true },
  { id: 'frase-168', texto: 'Às vezes, tudo o que alguém precisa é saber que não está sozinho.', autor: 'Autor desconhecido', categoria: 'Relacionamentos', ativo: true },
  { id: 'frase-169', texto: 'Deixe cada lugar um pouco melhor do que encontrou.', autor: 'Autor desconhecido', categoria: 'Relacionamentos', ativo: true },
];

export const phrasesPackageV1: PhraseBasePackage = {
  versaoBase: 1,
  frases,
};

export default phrasesPackageV1;
